name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Front-End repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install npm dependencies
        run: |
          cd Fragments
          npm install

      - name: Build npm packages
        run: |
          cd Fragments
          npm run build

      - name: Run npm tests
        run: |
          cd Fragments
          npm test -- --coverage

  eslint:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Front-End repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install modules
        run: |
          cd Fragments
          yarn

      - name: Run eslint
        run: |
          cd Fragments
          yarn run eslint src/ --ext .js --ext .jsx --color

  sonarcloud_analysis:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Front-End repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install npm dependencies
        run: |
          cd Fragments
          npm install
          npm test -- --coverage

      - name: SonarScanner for JS with pull request decoration support
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=ita-social-projects
            -Dsonar.projectKey=ita-social-projects_Fragments-front-end
            -Dsonar.javascript.lcov.reportPaths=Fragments/coverage/lcov.info
            -Dsonar.sources=./Fragments
            -Dsonar.exclusions=**/coverage/**,**/__tests__/**,**/__mocks__/**,**/styles/**,**/*test.jsx
            -Dsonar.verbose=true
            -Dsonar.coverage.exclusions=**/__tests__/**,**/__mocks__/**,**/coverage/**,**/styles/**,**/*test.jsx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
