name: ESLint
on:
  push:
    branches:
      - master
      - 24-add-ci-for-fragments-front-end #test branch
  pull_request:
    branches:
      - master
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  eslint:
      runs-on: ubuntu-latest
      steps:
        - name: Clone Front-End repo
          uses: actions/checkout@v3

        - name: Install modules
          run: |
            cd Fragments
            npm install -g eslint

        - name: Run eslint
          uses: stefanoeb/eslint-action@1.0.2
          with:
            files: Fragments/src/
